{
 "title": "Kubernetes: Apiserver Response Sizes",
 "tags": [
  "kubernetes",
  "apiserver"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "scope",
    "label": "Scope",
    "query": "label_values(apiserver_response_sizes_count, scope)"
   }
  ]
 },
 "panels": [
  {
   "title": "Response Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(apiserver_response_sizes_sum{scope=~\"$scope\"} / apiserver_response_sizes_count{scope=~\"$scope\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Response Size by Verb",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(apiserver_response_sizes_sum{scope=~\"$scope\"} / apiserver_response_sizes_count{scope=~\"$scope\"}) by(verb)",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "Top 5 Resources Response Sizes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg(apiserver_response_sizes_sum{scope=~\"$scope\"} / apiserver_response_sizes_count{scope=~\"$scope\"}) by(resource))",
     "legendFormat": "{{ resource }}"
    }
   ]
  }
 ]
}